[build]
  base = "."
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "dist"
  node_bundler = "esbuild"
  included_files = ["*.json", "*.js", "*.ts"]

[functions.index]
  # Specifically for the index function that handles OCR
  memory = 1024

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
